services:
  cinedex.presentation:
    image: cinedex.presentation
    build:
      context: .
      dockerfile: src/Cinedex.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
