name: .NET
run-name: >-
  ${{ github.event_name == 'pull_request'
      && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title)
      || github.event_name == 'workflow_dispatch'
      && format('manual: {0} â€¢ build #{1}.{2}', github.ref_name, github.run_number, github.run_attempt)
      || github.event.head_commit.message
  }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Publish
      run: |
        dotnet publish \
          --configuration Release \
          --no-build \
          --nologo \
          --output ./publish

    - name: Deploy to /home/felipe/apps/cinedex-api
      run: |
        rsync -av --delete ./publish/ /home/felipe/apps/cinedex-api/

    - name: Restart cinedex-api (user systemd)
      run: |
        export XDG_RUNTIME_DIR="/run/user/$(id -u)"
        systemctl --user restart cinedex-api.service

    - name: Show service status (debug)
      run: |
        export XDG_RUNTIME_DIR="/run/user/$(id -u)"
        systemctl --user --no-pager --full status cinedex-api.service
