# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
run-name: >-
  ${{ github.event_name == 'pull_request'
      && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title)
      || github.event_name == 'workflow_dispatch'
      && format('manual: {0} â€¢ build #{1}.{2}', github.ref_name, github.run_number, github.run_attempt)
      || github.event.head_commit.message
  }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # ðŸ‘ˆ enables "Run workflow" button

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Publish
      run: |
        dotnet publish \
          --configuration Release \
          --no-build \
          --nologo \
          --output ./publish
        
    - name: Deploy to /var/www/cinedex-api
      run: |
        rsync -av --delete ./publish/ /var/www/cinedex-api/

    - name: Restart cinedex-api service
      run: sudo systemctl restart kestrel-movie-svc.service
